spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.jeason.security.mapper: info